name: Implementación Actions

on:
  push:
    branches:
      - main

jobs:
  nombre_job:
    runs-on: ubuntu-latest
    steps:
      - name: Pinta el mensaje
        run: |
          echo "!Hola Pato¡"
      - name: Dime la fecha
        run: date
      - run: ls -l